_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 11
                - 48
                - 49
                - 55
            "2":
                - 1
                - 11
                - 48
                - 49
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.1
            "6": 4.45.0.dev0
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batchsize:
    value: 16
dataset:
    value: Bowl_Dataset (P02_01, P04_02, P14_05, P20_03)
epochs:
    value: 100
