name: 2haff_config
workspace: PI_Chalvatzaki
project: 2HAff

max_restarts: 0

resources:
  devices:
    - container_path: /dev/infiniband/
      host_path: /dev/infiniband/
      mode: mrw
  resource_pool: 42_Compute
  slots_per_trial: 1 # # GPUs

# entrypoint starts with "sh -c"
entrypoint: exec bash -c 'source /shared/2handedafforder/activate.bash && cd /shared/2handedafforder/ && bash pipeline.bash P25 P25_107 >> P25_107_log.txt'
#entrypoint: exec bash -c 'source /shared/2handedafforder/training/activate.bash && cd /shared/2handedafforder/training && python train_custom_sam.py --data-folder ../EPIC_DATA/hdf5_bowl --model-folder models_bowl >> test_log.txt'
#entrypoint: exec bash -c 'source /shared/2handedafforder/training/activate.bash && cd /shared/2handedafforder/clip_sam/model && python train_clip_sam.py --data-folder ../../EPIC_DATA/hdf5_categories --model-folder checkpoint_categories >> test_log.txt'


environment:
  add_capabilities:
    - IPC_LOCK
  drop_capabilities: null
  force_pull_image: false # Set to true to pull the image from the registry
  image: # docker image to use
    cpu: sjauhri/pearl_hessian_img:cpu
    cuda: sjauhri/pearl_hessian_img:cuda11.8

bind_mounts:
  - container_path: /pfss/mlde/mlde_ext
    host_path: /pfss/mlde/mlde_ext
    propagation: rprivate
    read_only: false
  - container_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki
  - container_path: /pfss/mlde/users/sj93qicy
    host_path: /pfss/mlde/users/sj93qicy
  - container_path: /shared
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/shared
  - container_path: /run/determined/workdir
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/home/sj93qicy

searcher:
    name: single
    metric: validation_loss
    max_length:
      epochs: 1