#!/pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/shared/2handedafforder/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from wheel.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
